services:
  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped
  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mosquitto
    environment:
      MQTT_BROKER: mosquitto
      MQTT_PORT: 1883
      DATABASE_URL: sqlite:///./smart_home.db
      JWT_SECRET: smarthome_secret_key_2025_licenta
      JWT_ALGORITHM: HS256
      JWT_EXPIRATION_MINUTES: 1440
      BASE_URL: http://91.98.118.24:8000
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USER: smarthomebydenis@gmail.com
      SMTP_PASSWORD: yesqsvhntgnxcpxq
      SMTP_FROM: smarthomebydenis@gmail.com
    volumes:
      - ./smart_home.db:/app/smart_home.db
    restart: unless-stopped
